 <!-- ========================
      Footer
    ========================== -->
    <footer class="footer">
      <div class="footer-primary">
        <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-6">
              <div class="footer-widget-about">
                <img src="assets/images/logo/logo-light.png" alt="logo" class="mb-30">
                <p class="color-gray" style="text-align: justify;">Our passion is to strive hard to manufacture & export world class Nutraceutical products in compliance with cGMP standards. We are committed to provide quality life to our country fellows by delivering them the most reliable and affordable access to export quality Nutraceutical products. We are dedicated to create motivating, unbiased working environment for our employees.
                </p>
                <a href="products.php" class="btn btn__primary btn__primary-style2 btn__link">
                  <span>Read More</span> <i class="icon-arrow-right"></i>
                </a>
              </div><!-- /.footer-widget__content -->
            </div><!-- /.col-xl-2 -->


      
           
            
            
            <div class="col-sm-12 col-md-6 col-lg-6">
              <div class="footer-widget-contact">
                <h6 style="margin-bottom: 0px !important;padding-bottom: 0px;"> Quick Contacts</h6>
                <ul class="contact-list list-unstyled">
                  <li>If you have any questions or need help, feel free to contact with our team.</li>
                  <li>
                    <a href="tel:(051) 4949539" class="phone__number">
                      <i class="icon-phone"></i> <span>Call : (051) 4949538-9</span>
                    </a>
                  </li>
                  
                  <hr>
                  
                  
                  <li class="color-body">
                    <h6 style="margin-bottom: 0px !important;padding-bottom: 0px;">Factory Address : </h6>
                    Small Industries Estate,Taxila, District Rawalpindi - 46000 Pakistan .
                  </li>
                </ul>
                <div class="d-flex align-items-center">
                  <a href="contact-us.php" class="btn btn__primary btn__link mr-30">
                    <i class="icon-arrow-right"></i> <span>Get Directions</span>
                  </a>
                  <ul class="social-icons list-unstyled mb-0" style="margin-left: 38%;">
                    <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                    <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                    <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                  </ul><!-- /.social-icons -->
                </div>
              </div><!-- /.footer-widget__content -->
            </div><!-- /.col-lg-2 -->
            
            
            <!--//
             <div class="col-sm-6 col-md-6 col-lg-2">
              <div class="footer-widget-nav">
                <h6 class="footer-widget__title">Links</h6>
                <nav>
                  <ul class="list-unstyled">
                   <li><a href="index.php"> Home</a></li>
                    <li><a href="about-us.php">About Us</a></li>
                    <li><a href="products.php">Products</a></li>
                    <li><a href="#">Distributors</a></li>
                    <li><a href="#">Get Quote</a></li>
                    <li><a href="faqs.php">FAQs</a></li>
                    <li><a href="contact-us.php">Contact Us</a></li>
                  </ul>
                </nav>
              </div><!-- /.footer-widget__content -->
            </div><!-- /.col-lg-2 -->
            
            
            
            
            
          
        </div><!-- /.container -->
      </div><!-- /.footer-primary -->
      <div class="footer-secondary">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-sm-12 col-md-6 col-lg-6">
              <span class="fz-14">&copy; 2020 Brooklyn Pharmaceuticals, All Rights Reserved. With Love by</span>
              <a class="fz-14 color-primary" href="www.bigbookcloud.com" target="new">Bigbookcloud.com</a>
            </div><!-- /.col-lg-6 -->
            <div class="col-sm-12 col-md-6 col-lg-6">
              <nav>
                <ul class="list-unstyled footer__copyright-links d-flex flex-wrap justify-content-end mb-0">
                  <li><a href="#">Terms & Conditions</a></li>
                  <li><a href="#">Privacy Policy</a></li>
                  <li><a href="#">Cookies</a></li>
                </ul>
              </nav>
            </div><!-- /.col-lg-6 -->
          </div><!-- /.row -->
        </div><!-- /.container -->
      </div><!-- /.footer-secondary -->
    </footer><!-- /.Footer -->