
<!-- =========================
    Header
=========================== -->
<header class="header header-layout2">
  <div class="header-topbar">
    <div class="container-fluid">
      <div class="row align-items-center">
        <div class="col-12">
          <div class="d-flex align-items-center justify-content-between">
            <ul class="contact__list d-flex flex-wrap align-items-center list-unstyled mb-0">
              <li>
                <i class="icon-phone"></i><a href="tel:+5565454117">Emergency Line: (051) 4949539</a>
              </li>
              <li>
                <i class="icon-location"></i><a href="#">Location: Brooklyn Pharmaceuticals, Taxila Rawalpindi</a>
              </li>
              <li>
                <i class="icon-clock"></i><a href="contact-us.php">Mon - Sat : 8:00 am - 5:00 pm</a>
              </li>
            </ul><!-- /.contact__list -->
            <div class="d-flex">
              <ul class="social-icons list-unstyled mb-0 mr-30">
                <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                <li><a href="#"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#"><i class="fab fa-twitter"></i></a></li>
              </ul><!-- /.social-icons -->
              <form class="header-topbar__search">
                <input type="text" class="form-control" placeholder="Search...">
                <button class="header-topbar__search-btn"><i class="fa fa-search"></i></button>
              </form>
            </div>
          </div>
        </div><!-- /.col-12 -->
      </div><!-- /.row -->
    </div><!-- /.container -->
  </div><!-- /.header-top -->


  <nav class="navbar navbar-expand-lg sticky-navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="index.php">
        
        <img src="assets/images/logo/logo-dark.png" class="logo-dark" alt="logo">
      </a>
      <button class="navbar-toggler" type="button">
        <span class="menu-lines"><span></span></span>
      </button>
      <div class="collapse navbar-collapse" id="mainNavigation">
        <ul class="navbar-nav ml-auto">

          <li class="nav__item">
            <a href="index.php"  class="nav__item-link active">Home</a>
          </li><!-- /.nav-item -->
          
          <li class="nav__item">
            <a href="about-us.php"  class="nav__item-link">About Us</a>
          </li><!-- /.nav-item -->


          <li class="nav__item">
            <a href="products.php"  class="nav__item-link">Products</a>
          </li><!-- /.nav-item -->


          <li class="nav__item">
            <a href="#"  class="nav__item-link">Distributors</a>
          </li><!-- /.nav-item -->

          
          <li class="nav__item">
            <a href="#"  class="nav__item-link">Get Quote</a>
          </li><!-- /.nav-item -->

          <li class="nav__item">
            <a href="faqs.php"  class="nav__item-link">FAQs</a>
          </li><!-- /.nav-item -->
 


          <li class="nav__item">
            <a href="contact-us.php"  class="nav__item-link">Contact Us</a>
          </li><!-- /.nav-item -->


          <li class="nav__item">
            <a href="#"  class="nav__item-link"></a>
          </li><!-- /.nav-item -->

          
        </ul><!-- /.navbar-nav -->
        <button class="close-mobile-menu d-block d-lg-none"><i class="fas fa-times"></i></button>
      </div><!-- /.navbar-collapse -->


    </div><!-- /.container -->
  </nav><!-- /.navabr -->
</header><!-- /.Header -->

