<?php
print "
<ul id=\"navigationMenu\">
    <li>
	    <a class=\"home\" href=\"../menu/menu.php\">
            <span>Menu</span>
        </a>
    </li>
    
    <li>
    	<a class=\"about\" href=\"../logout.php\">
            <span>Log Out</span>
        </a>
    </li>
    
    <li>
	     <a class=\"services\" href=\"ed_list.php\">
            <span>Manage Contant</span>
         </a>
    </li>
    
    <li>
    	<a class=\"portfolio\" href=\"change-password.php\">
            <span>Change Password</span>
        </a>
    </li>
    
    <li>
    	<a class=\"contact\" href=\"#\">
            <span>Contact us</span>
        </a>
    </li>
	
	<li>
    	<a class=\"close\" href=\"#\">
            X
			<span>Close</span>
        </a>
    </li>
</ul>
";
?>