<div class="navbar nav_title" style="border: 0;">
    <a href="index.php" class="site_title"><img src="images/<?php echo $logo;?>" alt="<?php echo $company;?>"/></a>
</div>
<div class="clearfix"></div>

<!-- menu prile quick info -->
<div class="profile">
    <div class="profile_pic">
        <img src="images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
        <span>Welcome,</span>
        <h2><?php echo $profile;?></h2>
    </div>
</div>