<?php 
$path = "../admin/orna/";
include_once('../admin/orna/db2.php');

if(isset($_GET['status'])){
    $_POST['status']=$_GET['status'];
}
$where=" where i.id=si.issue_id and m.id=si.machine_id ";

?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Itarat Al Jawdah | Invoice</title>
    
    <style>
        body,html{
            margin:0;
            padding:0 1em 1em 1em;
        }
        body{
            border-top:5px solid #0e4988;
        }
        .grey{
            background-color: #ececec;
            font-size: 0.7em;
        }
        .borders tr td, .borders{
            border:1px solid #fff;
            border-collapse: collapse;
        }
    .invoice-box{
        max-width:100%;
        font-size:16px;
        line-height:24px;
        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color:#555;
    }
    
    .invoice-box table{
        width:100%;
        text-align:left;
    }
    
    .invoice-box table td{
        padding:5px;
    }
    
    .invoice-box table tr td:nth-child(2){
        text-align:right;
    }
    
    
    
    .invoice-box table tr.top table td.title{
        font-size:45px;
        line-height:45px;
        color:#333;
    }
    
    .invoice-box table tr.heading td{
        font-size: 0.8em;
        background: #0e4988;
        border-bottom: 1px solid #0e4988;
        font-weight: bold;
        color: #fff;
    }
    
    .invoice-box table tr.details td{
        padding-bottom:1px;
    }
    
    .invoice-box table tr.item td{
        border-bottom:1px solid #eee;
    }
    
    .invoice-box table tr.item.last td{
        border-bottom:none;
    }
    
    .invoice-box table tr.total td:nth-child(2){
        border-top:2px solid #eee;
        font-weight:bold;
    }
    
    </style>
</head>

<body  style="font-size:0.8em;">
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td width="180px">
                                <img src="../images/logo.png" style="float:left;width:180px;">
                            </td>
                            
                            <td>
                                <h1>Total Service Calls</h1>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td width="50%" style="border-left:10px solid #3188ca;">
                                <p><b>Inquiry No : </b><br>
                                <b>Date : </b><?php echo date('D d-M-Y');?><br>
                                <b>For Month : </b><br>
                                <b>Generated By : </b>System</p>
                            </td>
                            
                            <td style="font-size:0.8em;">
                                
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
        <tr>
            <td colspan="2">
                <table>
                    <tr class="heading">
                        <td width="3%">Sr. #</td>
                        <td style="text-align:left;">Machine</td>
                        <td>Issue</td>
                        <td>Status</td>
                        <td>Notified on</td>
                        <td>Notified By</td>
                        <td>Action</td> 
                    </tr>

                    <?php
                        //------------Filter-----------------
                        if(isset($_POST['status']) && $_POST['status']!='*'){
                            if($where!=''){
                                $where.=' AND ';
                            }else{
                                $where.=" WHERE ";
                            }

                            $where.= "  `status`='".$_POST['status']."'";
                        }else{
                            $where.="";
                        }
                        //------------Filter-----------------

                        $sql="select si.* , si.dt as sidt,si.user as usersi, i.*, m.* from service_issue si,issue i, machine m ".$where." Order by si.id DESC";
                        $query=mysql_query($sql);
                            $sr=0;
                        while($result=mysql_fetch_array($query)){

                            $sql_user="select first_name, last_name from users where username = '".$result['usersi']."'";
                            $users=mysql_fetch_array(mysql_query($sql_user));

                            $sr++;
                            if($result['status']=='pending'){
                                    $status="<button type=\"button\" class=\"btn btn-warning btn-xs\">Pending</button>";
                                }
                            else if($result['status']=='Re-escalated'){
                                    $status="<button type=\"button\" class=\"btn btn-danger btn-xs\">Re-Escalated</button>";
                                }else{
                                    $status="<button type=\"button\" class=\"btn btn-success btn-xs\">Resolved</button>";
                                }
                            if($result['sidt']==''){
                                $result['sidt']=time();
                            }
                            print "
                            <tr class=\"details\" style=\"font-size:0.7em;\">
                                <td>".$sr."</td>
                                <td style=\"text-align:left;\">".utf8_encode($result['machine'])."</td>
                                <td>".$result['title']."</td>
                                <td>".$status."</td>
                                <td>".date('d-M-Y', $result['sidt'])."</td>
                                <td>".$users['first_name'].' '.$users['last_name']."</td>
                                <td>
                                    <a href=\"content-edit.php?id=".$result['id']."&t=service_issue\" class=\"btn btn-info btn-xs\"><i class=\"fa fa-pencil\"></i> Edit </a>
                                </td>
                            </tr>
                            ";
                        }
                    ?> 
                    </tr>
                    
                    <tr class="details" style="font-weight:bold">
                        <td colspan="5" style="text-align:right;">TOTAL: </td>
                        <td style="text-align:left;">123123</td>
                    </tr>
                </table>
            </td>
        </tr>
         
        
            
        <tr>
            <td style="width:40%;">
                <h4 style="line-height:16px;margin:0.1em;">Note:</h4>
                <p style="font-size:0.6em;margin:0.3em;">This report is system generated , No Signature required.</p>
            </td>
            <td></td>
        </tr>    
    </table>   
            
    </div>
</body>
</html>