<?php include_once('../admin/orna/db2.php');?>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Itarat Al Jawdah | Purchase Order</title>
    
    <style>
        body,html{
            margin:0;
            padding:0 1em 1em 1em;
        }
        body{
            border-top:5px solid #d60101;
        }
        .grey{
            background-color: #ececec;
            font-size: 0.7em;
        }
        .borders tr td, .borders{
            border:1px solid #fff;
            border-collapse: collapse !important;
        }
    
        .total td, .total{
            border:1px solid #d0d0d0;
            border-collapse: collapse;
            font-size: 0.9em;
            padding: 10px !important;
            line-height: 12px;
            font-weight: bold;
        }
        
    .invoice-box{
        max-width:100%;
        font-size:16px;
        line-height:24px;
        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color:#555;
    }
    
    .invoice-box table{
        width:100%;
        text-align:left;
    }
    
    .invoice-box table td{
        padding:5px;
    }
    
    .invoice-box table tr td:nth-child(2){
        text-align:right;
    }
    

    .invoice-box table tr.top table td.title{
        font-size:45px;
        line-height:45px;
        color:#333;
    }
    
    .invoice-box table tr.heading td{
        font-size: 0.8em;
        background: rgb(121, 121, 121);
        border-bottom: 1px solid #676363;
        font-weight: bold;
        color: #fff;
    }
    
    .invoice-box table tr.details td{
        padding-bottom:1px;
    }
    
    .invoice-box table tr.item td{
        border-bottom:1px solid #eee;
    }
    
    .invoice-box table tr.item.last td{
        border-bottom:none;
    }
    
    </style>
</head>

<body  style="font-size:0.8em;">
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td width="180px">
                                <img src="../images/logo 2.jpeg" style="float:left;width:180px;">
                            </td>
                            
                            <td style="background-color: #d60101;color: white;width: 100px;text-align: center;">
                                <h1>Purchase Order</h1>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <?php
                    //get supplier name
                    $sql_supplier="select * from supplier where id = '".@$_GET['supplier']."'";
                    $supplier=mysql_fetch_array(mysql_query($sql_supplier));


                    //get brand name
                    $sql_brand="select brand_name from brand where id = '".@$_GET['brand']."'";
                    $brand_name=mysql_fetch_array(mysql_query($sql_brand)); 
                    ?>
                    <table>
                        <tr>
                            <td width="50%" style="border-left:10px solid #d60101;">
                                <p style="text-align:left;font-size:0.8em;">
                                    <b><?php echo $supplier['name'];?></b><br>
                                    Mr./Miss. <?php echo $supplier['cont_person'];?><br>
                                    <?php echo $supplier['address'];?>
                                </p>
                            </td>
                            
                            <td style="font-size:0.8em;">
                                <p><b>P.O. No : </b><?php echo 'INQ'.str_pad(@$_GET['inquiry'],'6',0,STR_PAD_LEFT);?><br>
                                <b>Date : </b><?php echo date('D d-M-Y');?><br>
                                <b>For Month : </b><?php echo "<span style=\"text-transform:capitalize;\">".$_GET['month']."</span>-".$_GET['year'];?><br>
                                    <b>Generated By : </b>System</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
        <tr>
            <td colspan="2">
                <table>
                    <tr class="heading">
                        <td style="text-align:left;">Brand</td>
                        <td style="text-align:left;">Currency</td>
                        <td>Port of Delivery</td>
                        <td>Incoterm </td>
                        <td>Validity </td>
                        <td>ETD </td>
                    </tr>

                    <tr class="details" style="font-size:0.7em;">
                        <td><?php echo $brand_name['brand_name'];?></td>
                        <td style="text-align:left;">USD</td>
                        <td>Riyadh , KSA</td>
                        <td>FOB</td>
                        <td>7 Days </td>
                        <td>90 Days </td>
                    </tr>
                </table>
            </td>
        </tr>
         
        <tr>
            <td colspan="2">
                <table class="borders">    
                    <tr class="heading">
                        <td width="3%">Sr.</td>
                        <td style="text-align:left;">Size</td>
                        <td>Pattern</td>
                        <td width="6%">Ratings</td>
                        <td>SASO</td>
                        <td>Qty. Ordered</td>
                        <?php
                        $row='';
                        
                        if(@$_GET['type']=='unit_price' &&  @$_GET['type']!='size'){
                            print"<td>Unit Price</td>";
                            $row .= "<td></td>";
                        }
                        
                        if(@$_GET['type']=='target_price' &&  @$_GET['type']!='size'){
                            print"<td>Target Price</td>";
                            $row .= "<td></td>";
                        }
                        
                        ?>
                        
                        <td>Extended Price</td>
                        
                    </tr>
                    
                    <?php 
                        $sql="select 
                                `brand_item`.*, 
                                `inquiry_trans`.*,
                                `inquiry_trans`.id as inq_id, 
                                `pattern`.`name` as pattern_name, 
                                `pattern`.`rating` as pattern_rating,  
                                `brand`.*, 
                                `master_item`.`rating`
                                    FROM 
                                        `brand_item`,
                                        `inquiry_trans`, 
                                        `pattern`, 
                                        `brand`, 
                                        `master_item`
                                            WHERE 
                                                `inquiry_trans`.`inquiry_number`=".$_GET['inquiry']."
                                                AND `inquiry_trans`.`master_item`=`brand_item`.`id`  
                                                AND `brand_item`.`pattern_id`=`pattern`.`id`
                                                AND `brand_item`.`brand_id`=`brand`.`id`
                                                AND `pattern`.`id`=brand_item.pattern_id
                                                AND `master_item`.`item_number`=`brand_item`.`item_number`
                                                AND `brand_item`.`evaluate_id`<>5 
                                                AND `pattern`.`rating`>1
                                                AND `brand_item`.`saso_label`='Available'
                                                AND `master_item`.`rating`>0 
                                                AND `inquiry_trans`.`qty`>0
                                                AND `inquiry_trans`.`status`='Completed'
                                                    ORDER BY `brand_item`.`item_number` ASC "; 
                    $query=mysql_query($sql);                               
                    $sr=0;
                    $tot_qty=0;
                    while($result=mysql_fetch_array($query)){ 
                        $sr++;
                        $tot_qty+=$result['qty'];
                        print"
                            <tr class=\"details grey\">
                                <td>".$sr."</td>
                                <td style=\"text-align:left;\">".$result['item_number']."</td>
                                <td>".$result['pattern_name']."</td>
                                <td>".$result['pattern_rating']."/5</td>
                                <td>".$result['saso_label']."</td>    
                                <td>".$result['qty']."</td>
                                <td>$ ".$result['target_price']."</td>
                                <td>$ 1,231/-</td>
                            </tr>";
                    }
                    
                    ?>
                    
                    <tr class="details" style="font-weight:bold;margin-bottom:5px; border-bottom:2px solid #ececec;">
                        <td colspan="5" style="text-align:right;">TOTAL: </td>
                        <td style="text-align:left;"><?php echo $tot_qty;?></td>
                        <?php echo $row;?>
                        <td style="text-align:left;">$ 1,23,123/-</td>
                    </tr>
                </table>
            </td>
        </tr>
        
        <tr>
            <td style="width:20%;">
                <table class="report">
                    <tr>
                        <td colspan="3"><h4 style="line-height:12px;margin:0;padding:0;">Filler Sizes</h4></td>
                    </tr>
                    
                    <tr class="heading">
                        <td>Sr.</td>
                        <td style="text-align:left;">Item No.</td>
                        <td>QTY.</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>1</td>
                        <td style="text-align:left;">192R95/65</td>
                        <td>OPEN</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>1</td>
                        <td style="text-align:left;">192R95/65</td>
                        <td>200</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>1</td>
                        <td style="text-align:left;">192R95/65</td>
                        <td>100</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>1</td>
                        <td style="text-align:left;">192R95/65</td>
                        <td>30</td>
                    </tr>
                </table>
            </td>
            <td style="width:80%;">
            
                 <table style="width:70%;float:right;border-collapse: collapse;margin-top:1em;" >
                    
                    <!--<tr>
                        <td colspan="3"><h4 style="line-height:12px;margin:0;padding:0;">Gross Total</h4></td>
                    </tr>-->
                     
                    <tr class="total">
                        <td>Total Qty.</td>
                        <td style="text-align:left;">3200</td>
                    </tr>
                     
                     <tr class="total">
                        <td>Est. Containers</td>
                        <td style="text-align:left;">5</td>
                    </tr>
                     
                    <tr class="total">
                        <td>Freghit / Container </td>
                        <td style="text-align:left;">18787</td>
                    </tr>
                    
                    <tr class="total">
                        <td>Inspection (If Agreed)</td>
                        <td style="text-align:left;">1323</td>
                    </tr>
                     
                     <tr class="total">
                        <td>Others (If Applicable)</td>
                        <td style="text-align:left;">12676</td>
                    </tr>
                     
                     <tr style="background-color: #d60101 !important;
    color: white;">
                        <td>Total:</td>
                        <td style="text-align:left;">12676</td>
                    </tr>
                     
                    <tr style="font-size: 0.6em;font-style: italic;text-align: right;">
                        <td colspan="2">Five Thousand and Eight Hundred Only.</td>
                    </tr> 
                </table>
            </td>
        </tr>    
            
            
        <tr>
            <td style="width:40%;">
                <h4 style="line-height:16px;margin:0.1em;">Note:</h4>
                <p style="font-size:0.6em;margin:0.3em;line-height: 12px;">
                    1: The Tires Must have SASO Labels <br>
                    2: Tires must be of DOT 2017 <br>
                    3: Any older DOT tired will be discounted up tp 50% <br>
                    4: PO number should be printed on all related documents </p>
            </td>
            <td></td>
        </tr>    
    </table>   
            
    </div>
</body>
</html>