<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Itarat Al Jawdah | Invoice</title>
    
    <style>
        body,html{
            margin:0;
            padding:0 1em 1em 1em;
        }
        body{
            border-top:5px solid #d60101;
        }
        .grey{
            background-color: #ececec;
            font-size: 0.7em;
        }
        .borders tr td, .borders{
            border:1px solid #fff;
            border-collapse: collapse;
        }
    .invoice-box{
        max-width:100%;
        font-size:16px;
        line-height:24px;
        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color:#555;
    }
    
    .invoice-box table{
        width:100%;
        text-align:left;
    }
    
    .invoice-box table td{
        padding:5px;
    }
    
    .invoice-box table tr td:nth-child(2){
        text-align:right;
    }
    
    
    
    .invoice-box table tr.top table td.title{
        font-size:45px;
        line-height:45px;
        color:#333;
    }
    
    .invoice-box table tr.heading td{
        font-size: 0.8em;
        background: #d60101;
        border-bottom: 1px solid #d60101;
        font-weight: bold;
        color: #fff;
    }
    
    .invoice-box table tr.details td{
        padding-bottom:1px;
    }
    
    .invoice-box table tr.item td{
        border-bottom:1px solid #eee;
    }
    
    .invoice-box table tr.item.last td{
        border-bottom:none;
    }
    
    .invoice-box table tr.total td:nth-child(2){
        border-top:2px solid #eee;
        font-weight:bold;
    }
    
    </style>
</head>

<body  style="font-size:0.8em;">
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td width="180px">
                                <img src="http://localhost/erp/images/logo 2.jpeg" style="float:left;width:180px;">
                            </td>
                            
                            <td>
                                <h1>Purchase Inquiry</h1>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td width="50%" style="border-left:10px solid #d60101;">
                                <p style="text-align:left;font-size:0.8em;">
                                    <b>Kinforest Tyre Co. LTD</b><br>
                                    Mr./Miss Person: Betty<br>
                                    Room 513, Fazhan Building, TianAn High-Tech Garden, rnNo.730 Yingbin Road, Panyu District, Guangzhou, China
                                </p>
                            </td>
                            
                            <td style="font-size:0.8em;">
                                <p><b>Inquiry No : </b>INQ000069<br>
                                <b>Date : </b>01-Dec-2016<br>
                                <b>For Month : </b>January-2016<br>
                                    <b>Generated By : </b>System</p>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            
        <tr>
            <td colspan="2">
                <table>
                    <tr class="heading">
                        <td style="text-align:left;">Brand</td>
                        <td style="text-align:left;">Currency</td>
                        <td>Port of Delivery</td>
                        <td>Incoterm </td>
                        <td>Validity </td>
                    </tr>

                    <tr class="details" style="font-size:0.7em;">
                        <td>Kinforest</td>
                        <td style="text-align:left;">USD</td>
                        <td>Riyadh , KSA</td>
                        <td>FOB</td>
                        <td>7 Days </td>
                    </tr>
                </table>
            </td>
        </tr>
         
        <tr>
            <td colspan="2">
                <table class="borders">    
                    <tr class="heading">
                        <td width="3%">Sr.</td>
                        <td style="text-align:left;">Size</td>
                        <td>Pattern</td>
                        <td width="6%">Ratings</td>
                        <td>SASO</td>
                        <td>Qty.</td>
                        <td>Unit Price</td>
                        <td>Target Price</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>1</td>
                        <td style="text-align:left;">205/55R16</td>
                        <td>KF550</td>
                        <td>4/5</td>
                        <td>Available</td>
                        <td>200</td>
                        <td>$ 22.46</td>
                        <td>$ 12.36</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>2</td>
                        <td style="text-align:left;">205/55R16</td>
                        <td>KF550</td>
                        <td>4/5</td>
                        <td>Available</td>
                        <td>200</td>
                        <td>$ 22.46</td>
                        <td>$ 12.36</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>3</td>
                        <td style="text-align:left;">205/55R16</td>
                        <td>KF550</td>
                        <td>4/5</td>
                        <td>Available</td>
                        <td>200</td>
                        <td>$ 22.46</td>
                        <td>$ 12.36</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>4</td>
                        <td style="text-align:left;">205/55R16</td>
                        <td>KF550</td>
                        <td>4/5</td>
                        <td>Available</td>
                        <td>200</td>
                        <td>$ 22.46</td>
                        <td>$ 12.36</td>
                    </tr>
                    
                    <tr class="details grey">
                        <td>5</td>
                        <td style="text-align:left;">205/55R16</td>
                        <td>KF550</td>
                        <td>4/5</td>
                        <td>Available</td>
                        <td>200</td>
                        <td>$ 22.46</td>
                        <td>$ 12.36</td>
                    </tr>
                    
                    <tr class="details" style="font-weight:bold">
                        <td colspan="5" style="text-align:right;">TOTAL: </td>
                        <td style="text-align:left;">1200</td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
            </td>
        </tr>
            
        <tr>
            <td style="width:40%;">
                <h4 style="line-height:16px;margin:0.1em;">Note:</h4>
                <p style="font-size:0.6em;margin:0.3em;">This report is system generated , No Signature required.</p>
            </td>
            <td></td>
        </tr>    
    </table>   
            
    </div>
</body>
</html>